### PR TITLE
SEARCH: fixing issue 56, where words with uppercase letters are not found

### PR DESCRIPTION
**Pull request by jonamfischer**
This code also includes a consolidation of both KMP methods as we don't need to distinguish between a single word and multiple words.

### CODE REVIEW

**Comment by bpoldrack** [comment]
Just posting to make a record of the connection to #56 ;-)

**Comment by jonamfischer** [comment]
@bpoldrack Thanks ;-)

**Comment by bpoldrack** [comment]
Note, that such a PR can state `Closes #56` in its description or even better: have `(Closes #56)` in a commit message, @jonamfischer. ;-)
Thereby the issue will be closed by Github when this is merged and the mentioning shows up in the issue itself, so one can track that connection later on. Plus: The issue opener has a chance to notice, it was addressed.

**Comment by aqw** [comment]
@jonamfischer Thanks for the PR. Could you please rebase this on latest master?

**Comment by jonamfischer** [comment]
@aqw please note the updated descriptions in my PR.

**Comment by aqw** [comment]
Works great, and merged.

@jonamfischer  Thanks for the fix!

**Pull request merged**
